### ISSUE TITLE
UnboundLocalError: local variable 'table' referenced before assignment

### ISSUE THREAD

**Issue by 18z** [sgros/IPTablesRuleChecker#2]
I tried to execute IPTablesParser.py and the following msgs prompt out.

python src/IPTablesParser.py tests/parser.0001

Traceback (most recent call last):
  File "src/IPTablesParser.py", line 1591, in <module>
    main(sys.argv[1:])
  File "src/IPTablesParser.py", line 1560, in main
    firewall.addIPTablesLoadSavedStream(fwFileName, f)
  File "src/IPTablesParser.py", line 1407, in addIPTablesLoadSavedStream
    self.addIPTablesCLILine("iptables -t {} {}".format(table, line), lineNumber, fileName)

UnboundLocalError: local variable 'table' referenced before assignment

**Comment by sgros** [comment]
The problem is that the script expects iptables-save format of rules while you were giving it plain iptables commands. Anyway, I changed invocation code so that you have an option to specify which format input is in.

**Comment by 18z** [comment]
Thank you. :+1:
